[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.23"
optimizer = true
optimizer_runs = 1000000
via_ir = false

# ERC-4337 specific configurations
evm_version = "shanghai"

# Remappings for dependencies
remappings = [
    "@account-abstraction/=lib/account-abstraction/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/"
]

# Test configuration
fuzz = { runs = 256 }
verbosity = 3

# Gas reports
gas_reports = ["SimpleAccount", "SimpleAccountFactory"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
